version: '3'

services:
  app:
    build:
     dockerfile: Dockerfile.local
    ports:
     - "9000:8080"
    env_file: .env
    depends_on:
      - db
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - dbdatanew:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopass
volumes:
  dbdatanew:
